name: hamal

on:
  push:
    branches:
      - master

jobs:
  run:
    name: run
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch Credentials
        run: ./.github/scripts/fetch-google-service-account-credential.sh
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: Install dependencies
        run: |
          brew update
          brew install ffmpeg
          brew reinstall python
          pip3 install virtualenv
      - name: Run
        run: |
          virtualenv --python=python3 env
          source env/bin/activate
          pip install -r requirements.txt
          python main.py

